export const SECTION_ICONS: string[] = [
  'LayoutGrid',
  'LayoutDashboard',
  'Image',
  'FileText',
  'Type',
  'Star',
  'ShieldCheck',
  'Gift',
  'Heart',
  'Truck',
  'Package',
  'Zap',
  'Flame',
  'TrendingUp',
  'Clock',
  'Megaphone',
  'Tag',
  'ShoppingBag',
  'CheckCircle',
  'Info',
  'Bell',
  'ThumbsUp',
  'Users',
  'Globe',
  'Shield',
  'Leaf',
  'Gem',
  'Rocket',
  'Flower2',
  'Trophy',
];

export const SECTION_ICONS_MAP: Record<string, string> = {
  'marquee': 'Megaphone',
  'countdown': 'Clock',
  'hero': 'Rocket',
  'product-hero': 'ShoppingBag',
  'discount-cta': 'Gift',
  'info-banner': 'Info',
  'trust-banner': 'ShieldCheck',
  'product-select': 'Package',
  'reviews': 'Star',
  'order-form': 'FileText',
};
