/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── Legacy tokens (keep for backward compat) ── */
        primary: "rgb(var(--color-primary-rgb) / <alpha-value>)",
        "primary-light": "var(--color-primary-light)",
        accent: "rgb(var(--color-accent-rgb) / <alpha-value>)",
        "accent-light": "var(--color-accent-light)",
        secondary: "var(--color-secondary)",
        supporting: "rgb(var(--color-supporting-rgb) / <alpha-value>)",
        "background-light": "var(--color-background-light)",
        "background-dark": "var(--color-background-dark)",
        "surface-light": "rgb(var(--color-surface-rgb) / <alpha-value>)",
        "surface-dark": "#1e1e1e",
        "text-main": "var(--color-text-main)",
        "text-sub": "var(--color-text-sub)",
        "border-color": "var(--color-border)",
        /* ── Design system tokens (new) ── */
        "ds-bg":           "var(--color-bg)",
        "ds-surface":      "var(--color-surface)",
        "ds-surface-2":    "var(--color-surface-2)",
        "ds-border":       "var(--color-border-ds)",
        "ds-text":         "var(--color-text-primary)",
        "ds-text-sec":     "var(--color-text-secondary)",
        "ds-text-muted":   "var(--color-text-muted)",
        "ds-accent":       "var(--color-accent-ds)",
        "ds-accent-hover": "var(--color-accent-hover)",
        "ds-hero-bg":      "var(--color-hero-bg)",
        "ds-hero-text":    "var(--color-hero-text)",
        "ds-danger":       "var(--color-danger)",
        "ds-success":      "var(--color-success)",
        /* ── Semantic aliases used in admin components ── */
        "text-main-light":      "var(--color-text-primary)",
        "text-main-dark":       "var(--color-hero-text)",
        "text-secondary-light": "var(--color-text-secondary)",
        "border-light":         "var(--color-border-ds)",
        "border-dark":          "#333333",
      },
      fontFamily: {
        sans:    ["DM Sans", "Inter", "Helvetica Neue", "Arial", "sans-serif"],
        display: ["DM Sans", "Inter", "Helvetica Neue", "Arial", "sans-serif"],
        serif:   ["DM Sans", "Inter", "serif"],
        bengali: ["Hind Siliguri", "sans-serif"],
      },
      fontSize: {
        "ds-xs":   ["clamp(0.6875rem, 1vw, 0.75rem)",   { lineHeight: "1.5" }],
        "ds-sm":   ["clamp(0.75rem, 1.2vw, 0.875rem)",  { lineHeight: "1.5" }],
        "ds-base": ["clamp(0.875rem, 1.4vw, 1rem)",     { lineHeight: "1.6" }],
        "ds-lg":   ["clamp(1rem, 1.6vw, 1.125rem)",     { lineHeight: "1.6" }],
        "ds-xl":   ["clamp(1.125rem, 2vw, 1.375rem)",   { lineHeight: "1.4" }],
        "ds-2xl":  ["clamp(1.375rem, 2.5vw, 1.75rem)",  { lineHeight: "1.3" }],
        "ds-3xl":  ["clamp(1.625rem, 3vw, 2.25rem)",    { lineHeight: "1.2" }],
        "ds-4xl":  ["clamp(2rem, 4vw, 3rem)",            { lineHeight: "1.1" }],
        "ds-5xl":  ["clamp(2.5rem, 5vw, 4rem)",          { lineHeight: "1.1" }],
      },
      spacing: {
        "ds-1":  "clamp(0.25rem, 0.3vw, 0.25rem)",
        "ds-2":  "clamp(0.375rem, 0.5vw, 0.5rem)",
        "ds-3":  "clamp(0.625rem, 0.8vw, 0.75rem)",
        "ds-4":  "clamp(0.875rem, 1vw, 1rem)",
        "ds-5":  "clamp(1rem, 1.2vw, 1.25rem)",
        "ds-6":  "clamp(1.25rem, 1.5vw, 1.5rem)",
        "ds-8":  "clamp(1.5rem, 2vw, 2rem)",
        "ds-10": "clamp(2rem, 2.5vw, 2.5rem)",
        "ds-12": "clamp(2.25rem, 3vw, 3rem)",
        "ds-16": "clamp(3rem, 4vw, 4rem)",
        "ds-20": "clamp(3.75rem, 5vw, 5rem)",
        "ds-24": "clamp(4.5rem, 6vw, 6rem)",
      },
      borderRadius: {
        DEFAULT: "var(--radius-md)",
        sm:   "var(--radius-sm)",
        md:   "var(--radius-md)",
        lg:   "var(--radius-lg)",
        xl:   "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      transitionDuration: {
        DEFAULT: "150ms",
        fast: "150ms",
        base: "200ms",
      },
      maxWidth: {
        "site":    "1600px",
        "content": "1280px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
